import { Hono } from "hono";
import { toSSG } from "hono/ssg";
import { Style, css } from "hono/css";
import { jsxRenderer } from "hono/jsx-renderer";
import { serve } from "@hono/node-server";
import * as fs from "fs/promises";

const app = new Hono();

const styles = {
  main: css`
    margin: 0 auto;
    padding: 1rem;
    max-width: 800px;
    width: 100%;
  `,
  card: css`
    background-color: #f5f5f5;
    padding: 1rem;
    margin-bottom: 1rem;
    border-radius: 4px;
  `,
  cardTitle: css`
    margin: 0;
    margin-bottom: 0.5rem;
  `,
  cardContent: css`
    margin: 0;
  `,
};

const renderer = jsxRenderer(({ children, title }) => {
  return (
    <html>
      <head>
        <title>{title} - Hono SSG</title>
        <Style />
      </head>
      <body>
        <main class={styles.main}>{children}</main>
      </body>
    </html>
  );
});

app.get("/", renderer, (c) =>
  c.render(
    <div class={styles.card}>
      <h1 class={styles.cardTitle}>Hello, Hono!</h1>
      <p class={styles.cardContent}>
        This is a static site generated by Hono SSG.
      </p>
    </div>,
    { title: "Home" }
  )
);

if (process.env.MODE === "development") {
  serve(app);
} else {
  toSSG(app, fs);
}
